# 04.07
print('Введите любые ФИО полностью')
my_string = input()
print('Количество введенных символов: ', len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string)
print(my_string[0])
print(my_string[-1])
